name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    name: ${{ matrix.os }}-${{ matrix.os-version }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-${{ matrix.os-version }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - macOS
          - Windows
        os-version:
          - latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        include:
          - poetry-directory: $HOME/.local/bin
          - os: Windows
            poetry-directory: $APPDATA\Python\Scripts

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bootstrap poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y
          echo "${{ matrix.poetry-directory }}" >> $GITHUB_PATH

      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
          path: |
            .venv
            .tox

      - name: Check cache health
        if: steps.cache.outputs.cache-hit == 'true'
        run: timeout 5s .venv/bin/pip --version || rm -rf .venv

      - name: Install CI dependencies
        run: poetry install --no-ansi --no-root --only ci

      - name: Run code validation
        run: poetry run tox -e $(echo py${{ matrix.python-version }} | tr -d .)
